language: cpp
dist: bionic
sudo: true
compiler:
    - clang
    - gcc


# Install GTest properly since it is only available as a static library.
install:
    - mkdir ~/gtest_build
    - pushd ~/gtest_build
    - cmake /usr/src/gtest -DBUILD_SHARED_LIBS=true
    - make && sudo make install
    - popd

# Custom directory, for the correct year
before_script:
    - cd 2019

# CMake build
script: cmake . && make && make test

addons:
    apt:
        packages:
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libgtest-dev

cache:
    directories:
        - /home/travis/gtest_build
