language: cpp
dist: bionic
sudo: true

matrix:
    include:
        - addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-bionic-8
                packages:
                    - clang-8
                    - libc++-8-dev
                    - libc++abi-8-dev
                    - libboost-filesystem-dev
                    - libboost-program-options-dev
                    - libgtest-dev
          env:
            - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"


before_install:
    - eval "$MATRIX_EVAL"

# Install GTest properly since it is only available as a static library.
install:
    - mkdir -p ~/gtest_build
    - pushd ~/gtest_build
    - cmake /usr/src/gtest -DBUILD_SHARED_LIBS=true
    - make && sudo make install
    - popd

# Custom directory, for the correct year
before_script:
    - cd 2019

# CMake build
script: cmake . && make && make test
