language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

cache: cargo

# Custom directory, for the correct year
before_script:
    - cd 2018
