language: cpp
dist: bionic
compiler:
    - clang
    - gcc


# Custom directory, for the correct year
before_script:
    - cd 2019

# CMake build
script: cmake . && make && make test

addons:
    apt:
        packages:
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-test-dev
