[package]
name = "aoc-2018"
version = "0.1.0"
authors = ["Bert Peters <bert@bertptrs.nl>"]
description = "Implementation of the problems of Advent of Code 2018"

[dependencies]
clap = "2.32"
regex = "1.1.0"
chrono = "0.4.6"
itertools = "0.7.11"
